// Auto-generated by scripts/set-env.js from root .env. Do not edit manually.
export const environment = {
  production: false,
  apiUrl: 'http://localhost:4000/api/contact',
  turnstileSiteKey: '0x4AAAAAAEQ-YjNPCeMpVH-X',
};
