// Auto-generated by scripts/set-env.js from root .env. Do not edit manually.
export const environment = {
  production: true,
  apiUrl: '/api/contact',
  turnstileSiteKey: '0x4AAAAAAEQ-YjNPCeMpVH-X',
};
