import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load root .env or backend .env
dotenv.config({ path: path.resolve(__dirname, '../.env') });
dotenv.config({ path: path.resolve(__dirname, '../backend/.env') });

const siteKey =
  process.env.PUBLIC_TURNSTILE_SITE_KEY ||
  process.env.TURNSTILE_SITE_KEY ||
  '1x00000000000000000000AA'; // Official Cloudflare test site key fallback

const devApiUrl = process.env.DEV_API_URL || 'http://localhost:4000/api/contact';
const prodApiUrl = process.env.PROD_API_URL || '/api/contact';

const targetDir = path.resolve(__dirname, '../frontend/src/environments');
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

// Generate environment.ts
const devEnvContent = `// Auto-generated by scripts/set-env.js from root .env. Do not edit manually.
export const environment = {
  production: false,
  apiUrl: '${devApiUrl}',
  turnstileSiteKey: '${siteKey}',
};
`;

// Generate environment.prod.ts
const prodEnvContent = `// Auto-generated by scripts/set-env.js from root .env. Do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${prodApiUrl}',
  turnstileSiteKey: '${siteKey}',
};
`;

fs.writeFileSync(path.join(targetDir, 'environment.ts'), devEnvContent, 'utf8');
fs.writeFileSync(path.join(targetDir, 'environment.prod.ts'), prodEnvContent, 'utf8');

console.log('✓ Injected .env values into frontend environments');
